import { brand } from "@truss-harness/branding";
import * as vscode from "vscode";

export function agentControlCenterHtml(webview: vscode.Webview): string {
  const nonce = `${Date.now()}-${Math.random().toString(16).slice(2)}`;
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${webview.cspSource} 'unsafe-inline'; script-src 'nonce-${nonce}';"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
body { color: var(--vscode-foreground); background: var(--vscode-editor-background); font-family: var(--vscode-font-family); margin: 0; }
main { max-width: 920px; margin: 0 auto; padding: 24px; display: grid; gap: 20px; }
h1 { font-size: 20px; margin: 0; } h2 { font-size: 12px; letter-spacing: .6px; color: var(--vscode-descriptionForeground); margin: 0 0 9px; } p { color: var(--vscode-descriptionForeground); line-height: 1.5; margin: 5px 0 0; }
.top, .run-head, .approval-head { display: flex; align-items: center; justify-content: space-between; gap: 12px; } .card { display: grid; gap: 11px; padding: 14px; border: 1px solid var(--vscode-panel-border); border-radius: 6px; background: var(--vscode-sideBar-background); } .grid { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 2fr); gap: 12px; }
label { display: grid; gap: 5px; color: var(--vscode-descriptionForeground); font-size: 12px; } select, textarea { box-sizing: border-box; width: 100%; color: var(--vscode-input-foreground); background: var(--vscode-input-background); border: 1px solid var(--vscode-input-border); border-radius: 3px; padding: 7px; font: inherit; } textarea { min-height: 90px; resize: vertical; }
button { min-height: 30px; padding: 5px 10px; border: 1px solid var(--vscode-button-border, transparent); border-radius: 3px; color: var(--vscode-button-foreground); background: var(--vscode-button-background); cursor: pointer; } button.secondary { color: var(--vscode-foreground); background: transparent; border-color: var(--vscode-panel-border); } button.danger { color: var(--vscode-errorForeground); background: transparent; border-color: var(--vscode-errorForeground); } button:disabled { cursor: default; opacity: .55; }
.runs { display: grid; gap: 8px; } .run { display: grid; gap: 8px; padding: 12px; border: 1px solid var(--vscode-panel-border); border-radius: 5px; } .state { color: var(--vscode-terminal-ansiGreen); font-size: 12px; text-transform: capitalize; } .state.waiting_for_approval { color: var(--vscode-editorWarning-foreground); } .state.failed { color: var(--vscode-errorForeground); } .detail { color: var(--vscode-descriptionForeground); font-size: 12px; overflow-wrap: anywhere; } #approval { display: none; border-color: var(--vscode-editorWarning-foreground); } #approval.open { display: grid; } #status { min-height: 18px; color: var(--vscode-descriptionForeground); font-size: 12px; } #status.error { color: var(--vscode-errorForeground); } .empty { color: var(--vscode-descriptionForeground); font-style: italic; }
@media (max-width: 620px) { main { padding: 14px; } .grid { grid-template-columns: 1fr; } }
  /* Keep the full-size Agent Control Center visually aligned with the Chat view. */
  :root { --truss-green: #35c89a; --truss-green-strong: #1e9c78; --truss-green-soft: color-mix(in srgb, #35c89a 15%, transparent); --truss-border: color-mix(in srgb, var(--vscode-panel-border) 70%, #35c89a 30%); }
  body { background: var(--vscode-editor-background); }
  main { max-width: 980px; gap: 16px; padding: 28px; }
  .top { align-items: flex-start; }
  h1 { font-size: 24px; letter-spacing: -.25px; }
  h2 { color: var(--truss-green); font-size: 10px; font-weight: 800; letter-spacing: .8px; }
  .card { gap: 13px; padding: 16px; border-color: var(--truss-border); border-radius: 8px; background: color-mix(in srgb, var(--vscode-sideBar-background) 82%, var(--vscode-editor-background)); box-shadow: 0 5px 18px rgba(0, 0, 0, .08); }
  label { gap: 6px; font-weight: 600; }
  select, textarea { border-radius: 5px; }
  textarea:focus, select:focus { border-color: var(--truss-green); outline: 1px solid var(--truss-green); }
  button { min-height: 31px; border-color: var(--vscode-button-secondaryBorder, var(--vscode-panel-border)); border-radius: 5px; color: #06231b; background: var(--truss-green); font-weight: 700; transition: background-color 120ms ease, border-color 120ms ease; }
  button:hover { background: var(--truss-green-strong); border-color: var(--truss-green-strong); }
  button.secondary { color: var(--vscode-foreground); border-color: var(--vscode-panel-border); background: transparent; }
  button.secondary:hover { border-color: var(--truss-green); background: var(--truss-green-soft); }
  .run { gap: 10px; padding: 13px; border-color: var(--vscode-panel-border); border-radius: 7px; background: var(--vscode-editor-background); }
  .run:hover { border-color: var(--truss-border); }
  .run-head strong { font-size: 14px; }
  .state { color: var(--truss-green); font-size: 11px; font-weight: 700; letter-spacing: .25px; }
  .detail { line-height: 1.5; }
  #approval { border-color: var(--vscode-editorWarning-foreground); background: color-mix(in srgb, var(--vscode-editorWarning-foreground) 9%, var(--vscode-editor-background)); }
  #status { min-height: 20px; padding: 0 3px; }
  @media (max-width: 620px) { main { padding: 16px; } h1 { font-size: 21px; } .top { flex-direction: column; } }
</style></head><body><main>
<div class="top"><div><h1>Agent Control Center</h1><p>Run independent profiles in this workspace. Providers, models, and permissions remain local to VS Code.</p></div><button id="manage" class="secondary">Manage profiles</button></div>
<div class="card"><h2>START AN AGENT</h2><div class="grid"><label>Profile<select id="profile"></select></label><label>Task<textarea id="prompt" placeholder="Give this agent a focused task"></textarea></label></div><div><button id="start">Start agent</button></div></div>
<div id="approval" class="card"><div class="approval-head"><div><h2>TOOL APPROVAL</h2><strong id="approvalTitle">Agent needs approval</strong></div><span class="state waiting_for_approval">Waiting</span></div><p id="approvalInput"></p><div><button id="deny" class="danger">Deny</button> <button id="allow">Allow tool</button></div></div>
<section><div class="top"><h2>AGENT RUNS</h2><button id="refresh" class="secondary">Refresh</button></div><div id="runs" class="runs"><div class="empty">Loading agent profiles…</div></div></section><div id="status"></div>
</main><script nonce="${nonce}">
const vscode = acquireVsCodeApi();
const profiles = new Map(); const runs = new Map(); let pendingApproval;
const profileSelect = document.querySelector('#profile'); const prompt = document.querySelector('#prompt'); const runsElement = document.querySelector('#runs'); const status = document.querySelector('#status'); const approval = document.querySelector('#approval');
const post = (message) => vscode.postMessage(message);
const setStatus = (message, error = false) => { status.textContent = message || ''; status.className = error ? 'error' : ''; };
const text = (tag, value, className) => { const element = document.createElement(tag); element.textContent = value; if (className) element.className = className; return element; };
const active = (state) => ['queued', 'running', 'waiting_for_approval'].includes(state);
function renderProfiles() { const selected = profileSelect.value; profileSelect.replaceChildren(); for (const profile of profiles.values()) { const option = document.createElement('option'); option.value = profile.id; option.textContent = profile.displayName + ' — ' + profile.provider + '/' + profile.model + ' · ' + profile.mode; profileSelect.append(option); } if (profiles.has(selected)) profileSelect.value = selected; document.querySelector('#start').disabled = profiles.size === 0; }
function renderRuns() { runsElement.replaceChildren(); if (!runs.size) { runsElement.append(text('div', 'No agent runs yet.', 'empty')); return; } for (const run of [...runs.values()].reverse()) { const owner = profiles.get(run.agentId); const card = document.createElement('article'); card.className = 'run'; const head = document.createElement('div'); head.className = 'run-head'; const name = document.createElement('div'); name.append(text('strong', owner ? owner.displayName : 'Managed agent')); name.append(text('div', owner ? owner.provider + '/' + owner.model : run.agentId, 'detail')); head.append(name); head.append(text('span', run.state.replaceAll('_', ' '), 'state ' + run.state)); card.append(head); if (run.latestProgress) card.append(text('div', run.latestProgress, 'detail')); if (run.output) card.append(text('pre', run.output, 'detail')); if (run.activeTool) card.append(text('div', 'Active tool: ' + run.activeTool.name, 'detail')); if (run.changedFiles && run.changedFiles.length) card.append(text('div', run.changedFiles.length + ' changed file' + (run.changedFiles.length === 1 ? '' : 's'), 'detail')); if (run.error) card.append(text('div', run.error, 'detail')); if (active(run.state)) { const stop = text('button', 'Stop agent', 'danger'); stop.onclick = () => post({ type: 'stop', runId: run.id }); card.append(stop); } runsElement.append(card); } }
function renderApproval() { if (!pendingApproval) { approval.className = 'card'; return; } approval.className = 'card open'; document.querySelector('#approvalTitle').textContent = 'Allow ' + pendingApproval.tool.replaceAll('_', ' ') + '?'; document.querySelector('#approvalInput').textContent = JSON.stringify(pendingApproval.input, null, 2); }
document.querySelector('#start').onclick = () => { const task = prompt.value.trim(); if (!task) return setStatus('Enter a task before starting an agent.', true); post({ type: 'start', agentId: profileSelect.value, prompt: task }); prompt.value = ''; };
document.querySelector('#refresh').onclick = () => post({ type: 'ready' }); document.querySelector('#manage').onclick = () => post({ type: 'manageProfiles' }); document.querySelector('#allow').onclick = () => { if (pendingApproval) post({ ...pendingApproval, type: 'resolveApproval', approved: true }); pendingApproval = undefined; renderApproval(); }; document.querySelector('#deny').onclick = () => { if (pendingApproval) post({ ...pendingApproval, type: 'resolveApproval', approved: false }); pendingApproval = undefined; renderApproval(); };
window.addEventListener('message', ({ data: message }) => { if (message.type === 'state') { profiles.clear(); runs.clear(); for (const profile of message.profiles || []) profiles.set(profile.id, profile); for (const run of message.runs || []) runs.set(run.id, run); renderProfiles(); renderRuns(); setStatus(''); } if (message.type === 'run') { runs.set(message.run.id, message.run); renderRuns(); } if (message.type === 'approval') { pendingApproval = message; renderApproval(); } if (message.type === 'error') setStatus(message.message, true); });
post({ type: 'ready' });
</script></body></html>`;
}

export function webviewHtml(
  webview: vscode.Webview,
  extensionUri: vscode.Uri,
): string {
  const nonce = `${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const logoUri = webview.asWebviewUri(
    vscode.Uri.joinPath(extensionUri, "media", "truss-harness.png"),
  );
  return String.raw`<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src ${webview.cspSource} data:; style-src 'unsafe-inline'; script-src 'nonce-${nonce}';">
<style>
  :root { color-scheme: light dark; font-family: var(--vscode-font-family); color: var(--vscode-foreground); background: var(--vscode-sideBar-background); }
  html, body { width: 100%; height: 100%; min-height: 0; overflow: hidden; } * { box-sizing: border-box; } body { position: fixed; inset: 0; margin: 0; min-width: 0; display: flex; flex-direction: column; overflow: hidden; font-size: 13px; }
  button, select, input, textarea { font: inherit; color: var(--vscode-input-foreground); background: var(--vscode-input-background); border: 1px solid var(--vscode-input-border); border-radius: 4px; }
  button { min-height: 28px; padding: 4px 8px; cursor: pointer; } button:hover { background: var(--vscode-button-hoverBackground); } button.primary { color: var(--vscode-button-foreground); background: var(--vscode-button-background); border-color: var(--vscode-button-background); }
  button:focus-visible, select:focus-visible, input:focus-visible, textarea:focus-visible { outline: 1px solid var(--vscode-focusBorder); outline-offset: 1px; }
  header { flex: 0 0 auto; padding: 11px 10px 9px; border-bottom: 1px solid var(--vscode-panel-border); display: grid; gap: 9px; background: var(--vscode-sideBar-background); } .brand-row, .actions, .segmented { display: flex; align-items: center; gap: 5px; min-width: 0; } .brand { font-weight: 700; letter-spacing: .2px; white-space: nowrap; margin-right: auto; } #modelStatus { color: var(--vscode-descriptionForeground); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .segmented { padding: 2px; border: 1px solid var(--vscode-panel-border); border-radius: 5px; } .segmented button { border: 0; background: transparent; min-height: 24px; padding: 3px 7px; } .segmented button.active { background: var(--vscode-button-background); color: var(--vscode-button-foreground); box-shadow: inset 0 0 0 1px var(--vscode-focusBorder); }
  #telemetry { display: grid; grid-template-columns: minmax(130px, 1fr) auto; align-items: center; gap: 10px; min-width: 0; color: var(--vscode-descriptionForeground); font-size: 11px; } .telemetry-context { min-width: 0; display: grid; grid-template-columns: auto minmax(52px, 1fr); gap: 5px 7px; align-items: center; } .telemetry-label { color: var(--vscode-descriptionForeground); font-size: 10px; font-weight: 700; letter-spacing: .35px; } #contextValue, #rateValue { color: var(--vscode-foreground); font-variant-numeric: tabular-nums; white-space: nowrap; } .meter { height: 4px; min-width: 0; overflow: hidden; background: var(--vscode-progressBar-background); border-radius: 999px; } .meter > span { display: block; width: 0; height: 100%; background: var(--vscode-progressBar-background, var(--vscode-focusBorder)); border-radius: inherit; transition: width 120ms linear, background-color 120ms linear; } .meter > span.active { background: var(--vscode-focusBorder); } .meter > span.warning { background: var(--vscode-editorWarning-foreground); } .meter > span.critical { background: var(--vscode-editorError-foreground); }
  #settings { display: none; flex: 0 1 auto; max-height: 52vh; overflow: auto; padding: 10px; gap: 8px; border-bottom: 1px solid var(--vscode-panel-border); background: var(--vscode-editor-background); } #settings.open { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); } label { min-width: 0; display: grid; gap: 4px; color: var(--vscode-descriptionForeground); font-size: 11px; } input, select { width: 100%; min-width: 0; padding: 5px 6px; } #settings .actions { align-self: end; }
  #workspace { flex: 1 1 0; min-width: 0; min-height: 0; overflow: hidden; display: grid; grid-template-columns: minmax(118px, 30%) minmax(0, 1fr); } #history { min-width: 0; min-height: 0; overflow-y: auto; overflow-x: hidden; border-right: 1px solid var(--vscode-panel-border); padding: 7px; } .history-title { color: var(--vscode-descriptionForeground); font-size: 11px; text-transform: uppercase; margin: 2px 3px 7px; } .conversation-row { display: grid; grid-template-columns: minmax(0, 1fr) 24px; align-items: center; margin-bottom: 2px; } .conversation { display: block; width: 100%; text-align: left; background: transparent; border: 0; border-radius: 3px; padding: 6px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; } .conversation.active { background: var(--vscode-list-activeSelectionBackground); color: var(--vscode-list-activeSelectionForeground); } .delete-conversation { min-height: 24px; padding: 0; border: 0; background: transparent; color: var(--vscode-descriptionForeground); } .delete-conversation:hover { color: var(--vscode-errorForeground); background: var(--vscode-list-hoverBackground); }
  #chat { min-width: 0; min-height: 0; height: 100%; padding: 12px; overflow-y: auto; overflow-x: hidden; overscroll-behavior: contain; display: flex; flex-direction: column; gap: 12px; } .plan { display: grid; gap: 4px; padding: 8px; border: 1px solid var(--vscode-panel-border); border-radius: 4px; background: var(--vscode-textBlockQuote-background); font-size: 12px; } .plan strong { overflow-wrap: anywhere; } .plan-step { overflow-wrap: anywhere; color: var(--vscode-descriptionForeground); } .plan-step.in_progress { color: var(--vscode-editorWarning-foreground); } .plan-step.completed { color: var(--vscode-terminal-ansiGreen); text-decoration: line-through; } .empty { color: var(--vscode-descriptionForeground); line-height: 1.5; margin: auto 0; } .message { white-space: pre-wrap; line-height: 1.5; overflow-wrap: anywhere; } .message-header { color: var(--vscode-descriptionForeground); font-size: 11px; font-weight: 700; margin-bottom: 3px; } .message.user { padding-left: 8px; border-left: 2px solid var(--vscode-focusBorder); } .message.assistant { padding-left: 8px; border-left: 2px solid var(--vscode-terminal-ansiGreen); } .tool { padding: 7px; border: 1px solid var(--vscode-panel-border); background: var(--vscode-textBlockQuote-background); border-radius: 4px; color: var(--vscode-descriptionForeground); } .tool button { margin: 6px 4px 0 0; }
  #composer { flex: 0 0 auto; min-width: 0; min-height: 0; position: relative; z-index: 1; display: grid; grid-template-columns: minmax(0, 1fr) auto auto auto; gap: 6px; padding: 9px 10px 6px; border-top: 1px solid var(--vscode-panel-border); background: var(--vscode-sideBar-background); box-shadow: 0 -3px 10px color-mix(in srgb, var(--vscode-sideBar-background) 78%, transparent); } textarea { min-height: 36px; max-height: 120px; resize: vertical; padding: 7px; } #attachments { grid-column: 1 / -1; display: flex; flex-wrap: wrap; gap: 5px; } .attachment { display: inline-flex; align-items: center; gap: 5px; max-width: 180px; padding: 3px 5px; border: 1px solid var(--vscode-panel-border); background: var(--vscode-textBlockQuote-background); font-size: 11px; } .attachment span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; } .attachment img { width: 32px; height: 28px; object-fit: cover; } .attachment button { min-height: 20px; padding: 0 4px; } .message-attachments { display: flex; flex-wrap: wrap; gap: 5px; margin-top: 7px; } #stop { display: none; } body.streaming #stop { display: inline-block; } body.streaming #send { display: none; } #agentControls { flex: 0 0 auto; min-width: 0; display: grid; grid-template-columns: auto minmax(0, 1fr) auto; gap: 7px; align-items: center; padding: 0 10px 9px; background: var(--vscode-sideBar-background); } .quick-model { min-width: 0; display: grid; grid-template-columns: auto minmax(0, 1fr); align-items: center; gap: 5px; } .quick-model span { color: var(--vscode-descriptionForeground); font-size: 10px; font-weight: 700; letter-spacing: .35px; } #quickModel { min-width: 0; height: 28px; padding: 3px 6px; }
  .message { white-space: normal; } .markdown > :first-child { margin-top: 0; } .markdown > :last-child { margin-bottom: 0; } .markdown p { margin: 0 0 8px; white-space: pre-wrap; } .markdown h1, .markdown h2, .markdown h3, .markdown h4 { margin: 12px 0 6px; font-size: 14px; line-height: 1.35; } .markdown ul { margin: 4px 0 8px; padding-left: 19px; } .markdown blockquote { margin: 7px 0; padding-left: 8px; border-left: 2px solid var(--vscode-textBlockQuote-border); color: var(--vscode-descriptionForeground); } .markdown code { padding: 1px 4px; border-radius: 3px; background: var(--vscode-textCodeBlock-background); font-family: var(--vscode-editor-font-family); font-size: .92em; } .thinking { color: var(--vscode-descriptionForeground); font-size: 12px; white-space: nowrap; animation: thinking-pulse 1.2s ease-in-out infinite; } @keyframes thinking-pulse { 0%, 100% { opacity: .45; } 50% { opacity: 1; } } .code-block { min-width: 0; max-width: 100%; overflow: hidden; margin: 9px 0; border: 1px solid var(--vscode-panel-border); border-radius: 4px; background: var(--vscode-textCodeBlock-background); } .code-language { padding: 4px 8px; border-bottom: 1px solid var(--vscode-panel-border); color: var(--vscode-descriptionForeground); font-family: var(--vscode-editor-font-family); font-size: 10px; text-transform: uppercase; } .code-block pre { min-width: 0; margin: 0; overflow: hidden; padding: 9px; white-space: pre-wrap; overflow-wrap: anywhere; word-break: break-word; } .code-block code { display: block; min-width: 0; padding: 0; background: transparent; font-family: var(--vscode-editor-font-family); font-size: 12px; line-height: 1.55; white-space: inherit; overflow-wrap: inherit; word-break: inherit; } .token-comment { color: var(--vscode-editorCodeLens-foreground); } .token-string { color: var(--vscode-terminal-ansiYellow); } .token-keyword { color: var(--vscode-terminal-ansiBlue); } .token-number { color: var(--vscode-terminal-ansiMagenta); } .markdown a { color: var(--vscode-textLink-foreground); } #composer { position: relative; } #slashMenu { position: absolute; z-index: 4; right: 10px; bottom: calc(100% - 2px); left: 10px; max-height: 220px; overflow: auto; padding: 4px; border: 1px solid var(--vscode-panel-border); border-radius: 4px; background: var(--vscode-editorWidget-background); box-shadow: 0 -8px 24px #0006; } .slash-option { display: block; width: 100%; min-height: 27px; border: 0; border-radius: 3px; background: transparent; text-align: left; font-family: var(--vscode-editor-font-family); font-size: 12px; } .slash-option:hover, .slash-option.active { background: var(--vscode-list-activeSelectionBackground); color: var(--vscode-list-activeSelectionForeground); }
  @media (max-width: 700px) { #settings.open { grid-template-columns: repeat(2, minmax(0, 1fr)); } } @media (max-width: 560px) { header { padding: 8px; } .brand-row { flex-wrap: wrap; } #telemetry { width: 100%; } #workspace { grid-template-columns: 1fr; grid-template-rows: auto minmax(0, 1fr); } #history { display: flex; gap: 4px; overflow-x: auto; overflow-y: hidden; padding: 5px; border-right: 0; border-bottom: 1px solid var(--vscode-panel-border); } .history-title { display: none; } .conversation-row { display: flex; min-width: 122px; } .conversation { width: auto; min-width: 96px; } #settings.open { grid-template-columns: 1fr; } #composer { grid-template-columns: minmax(0, 1fr) auto; } #stop, #send { grid-column: 2; } #agentControls { grid-template-columns: 1fr; } .quick-model { grid-template-columns: auto minmax(0, 1fr); } }
  /* Truss webview polish: keep VS Code's theme tokens, with a restrained green accent. */
  :root { --truss-green: #35c89a; --truss-green-strong: #1e9c78; --truss-green-soft: color-mix(in srgb, #35c89a 17%, transparent); --truss-surface: color-mix(in srgb, var(--vscode-sideBar-background) 82%, var(--vscode-editor-background)); --truss-border: color-mix(in srgb, var(--vscode-panel-border) 72%, #35c89a 28%); }
  body { letter-spacing: .01em; background: var(--vscode-sideBar-background); }
  button { border-color: var(--vscode-button-secondaryBorder, var(--vscode-input-border)); background: var(--vscode-button-secondaryBackground, var(--vscode-input-background)); transition: background-color 120ms ease, border-color 120ms ease, color 120ms ease; }
  button:hover { background: var(--vscode-button-secondaryHoverBackground, var(--vscode-list-hoverBackground)); border-color: var(--truss-border); }
  button.primary { color: #06231b; background: var(--truss-green); border-color: var(--truss-green); font-weight: 700; }
  button.primary:hover { background: var(--truss-green-strong); border-color: var(--truss-green-strong); }
  header { gap: 10px; padding: 12px 12px 10px; border-bottom-color: var(--truss-border); box-shadow: 0 3px 14px rgba(0, 0, 0, .08); }
  .brand-row { display: grid; grid-template-columns: minmax(0, 1fr) auto; justify-content: stretch; gap: 10px; }
  .brand-lockup { display: inline-flex; align-items: center; gap: 7px; min-width: 0; }
  .brand-mark { width: 26px; height: 26px; border-radius: 7px; object-fit: contain; }
  .brand { margin-right: 0; color: var(--vscode-foreground); font-size: 14px; }
  .header-actions { display: flex; align-items: center; justify-content: flex-end; flex-wrap: nowrap; gap: 5px; min-width: 0; }
  #headerAction { width: 126px; min-height: 29px; padding: 4px 25px 4px 8px; border-color: var(--truss-green); background: var(--truss-green-soft); color: var(--vscode-foreground); font-size: 11px; font-weight: 600; }
  #telemetry { padding: 7px 8px; border: 1px solid var(--vscode-panel-border); border-radius: 6px; background: var(--truss-surface); }
  .telemetry-label { color: var(--truss-green); }
  .meter { background: var(--vscode-editorWidget-border); }
  .meter > span.active { background: var(--truss-green); }
  #settings { gap: 12px; padding: 14px 12px 16px; border-bottom-color: var(--truss-border); background: var(--vscode-editor-background); }
  #settings.open { display: flex; flex-direction: column; align-items: stretch; }
  .settings-intro { grid-column: 1 / -1; display: flex; align-items: end; justify-content: space-between; gap: 14px; padding: 0 0 10px; border-bottom: 1px solid var(--vscode-panel-border); }
  .settings-intro span { display: block; margin-bottom: 3px; color: var(--truss-green); font-size: 10px; font-weight: 800; letter-spacing: .7px; }
  .settings-intro strong { font-size: 14px; }
  .settings-intro p { max-width: 400px; margin: 0; color: var(--vscode-descriptionForeground); font-size: 11px; line-height: 1.45; }
  .settings-section { min-width: 0; display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; padding: 11px; border: 1px solid var(--vscode-panel-border); border-radius: 8px; background: var(--truss-surface); }
  .settings-section.full-width { grid-column: 1 / -1; }
  .settings-section .full-width-label { grid-column: 1 / -1; }
  .settings-section-heading { grid-column: 1 / -1; display: flex; align-items: baseline; justify-content: space-between; gap: 9px; padding-bottom: 7px; border-bottom: 1px solid var(--vscode-panel-border); }
  .settings-section-heading strong { color: var(--vscode-foreground); font-size: 12px; }
  .settings-section-heading span { color: var(--vscode-descriptionForeground); font-size: 10px; line-height: 1.35; text-align: right; }
  #settings label { gap: 5px; font-weight: 600; }
  body.vscode-dark, body.vscode-high-contrast { color-scheme: dark; }
  body.vscode-light, body.vscode-high-contrast-light { color-scheme: light; }
  #settings input, #settings select, #settings textarea { border-color: var(--vscode-input-border); background: var(--vscode-input-background); }
  select { color-scheme: inherit; color: var(--vscode-dropdown-foreground, var(--vscode-input-foreground)); background: var(--vscode-dropdown-background, var(--vscode-input-background)); }
  select option, select optgroup { color: var(--vscode-dropdown-foreground, var(--vscode-input-foreground)); background-color: var(--vscode-dropdown-background, var(--vscode-input-background)); }
  .model-picker { position: relative; min-width: 0; display: grid; gap: 5px; color: var(--vscode-descriptionForeground); font-size: 11px; font-weight: 600; }
  #modelPickerButton { width: 100%; min-height: 30px; overflow: hidden; padding-right: 26px; border-color: var(--vscode-input-border); background: var(--vscode-input-background); color: var(--vscode-input-foreground); text-align: left; text-overflow: ellipsis; white-space: nowrap; }
  #modelPickerButton[aria-expanded="true"] { border-color: var(--truss-green); box-shadow: 0 0 0 1px var(--truss-green); }
  #modelPickerMenu { position: absolute; z-index: 10; top: calc(100% + 5px); right: 0; left: 0; display: grid; gap: 6px; min-width: 250px; padding: 7px; border: 1px solid var(--truss-border); border-radius: 7px; color: var(--vscode-dropdown-foreground, var(--vscode-input-foreground)); background: var(--vscode-dropdown-background, var(--vscode-editorWidget-background, var(--vscode-input-background))); box-shadow: 0 8px 24px rgba(0, 0, 0, .36); }
  #modelPickerMenu[hidden] { display: none; }
  #modelPickerSearch { padding: 6px 7px; }
  #modelPickerOptions { max-height: 250px; overflow: auto; display: grid; gap: 2px; }
  .model-picker-option { width: 100%; min-height: 34px; display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 7px; align-items: center; padding: 6px 7px; border: 0; border-radius: 4px; background: transparent; color: var(--vscode-foreground); text-align: left; }
  .model-picker-option:hover, .model-picker-option[aria-selected="true"] { background: color-mix(in srgb, var(--truss-green) 17%, var(--vscode-list-hoverBackground)); }
  .model-picker-name { min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-family: var(--vscode-editor-font-family); font-size: 11px; }
  .model-picker-meta { color: var(--vscode-descriptionForeground); font-size: 10px; font-variant-numeric: tabular-nums; text-align: right; white-space: nowrap; }
  .model-picker-empty { padding: 7px; color: var(--vscode-descriptionForeground); font-size: 11px; }
  #settings input[readonly], #settings input:disabled { color: var(--vscode-descriptionForeground); background: var(--vscode-disabledForeground, var(--vscode-editor-inactiveSelectionBackground)); cursor: default; }
  #settings .provider-status { min-height: 18px; color: var(--vscode-descriptionForeground); font-size: 11px; line-height: 1.45; }
  #settings .provider-status.connected { color: var(--truss-green); }
  #settings .provider-status.failed { color: var(--vscode-errorForeground); }
  #settings .actions { position: relative; z-index: 1; grid-column: 1 / -1; display: flex; align-items: center; justify-content: flex-end; flex-wrap: wrap; gap: 6px; padding-top: 2px; }
  #settings .actions #apply { min-width: 78px; }
  #workspace { border-top: 0; background: var(--vscode-editor-background); }
  #history { padding: 9px 7px; border-right-color: var(--truss-border); background: var(--truss-surface); }
  .history-title { margin: 2px 5px 8px; color: var(--truss-green); font-size: 10px; font-weight: 800; letter-spacing: .75px; }
  .conversation-row { margin-bottom: 4px; }
  .conversation { min-height: 29px; padding: 6px 7px; color: var(--vscode-descriptionForeground); }
  .conversation:hover { background: var(--vscode-list-hoverBackground); color: var(--vscode-foreground); }
  .conversation.active { color: #e8fff8; background: color-mix(in srgb, var(--truss-green) 22%, var(--vscode-list-activeSelectionBackground)); box-shadow: inset 2px 0 0 var(--truss-green); }
  .delete-conversation { border-radius: 3px; }
  #chat { gap: 14px; padding: 16px; background: var(--vscode-editor-background); }
  .empty { max-width: 370px; margin: auto; padding: 18px; border: 1px dashed var(--truss-border); border-radius: 8px; background: var(--truss-surface); text-align: center; }
  .plan, .tool { border-color: var(--truss-border); border-radius: 7px; background: var(--truss-surface); }
  .plan { gap: 6px; padding: 10px; }
  .message { padding: 10px 11px; border: 1px solid transparent; border-radius: 7px; background: color-mix(in srgb, var(--vscode-editor-background) 88%, var(--vscode-sideBar-background)); }
  .message.user { border-left: 3px solid var(--vscode-focusBorder); background: color-mix(in srgb, var(--vscode-list-hoverBackground) 70%, transparent); }
  .message.assistant { border-color: color-mix(in srgb, var(--truss-green) 22%, var(--vscode-panel-border)); border-left: 3px solid var(--truss-green); }
  .message-header { color: var(--truss-green); font-size: 10px; letter-spacing: .65px; }
  .message.user .message-header { color: var(--vscode-focusBorder); }
  .tool { padding: 9px 10px; color: var(--vscode-descriptionForeground); }
  #composer { display: grid; grid-template-columns: minmax(0, 1fr); gap: 7px; padding: 10px 12px 8px; border-top-color: var(--truss-border); background: var(--truss-surface); box-shadow: 0 -6px 18px rgba(0, 0, 0, .09); }
  #composerRow { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 7px; min-width: 0; }
  #composerRow > button { min-width: 76px; }
  #composer textarea { min-height: 42px; padding: 9px; border-color: var(--vscode-input-border); }
  #composer textarea:focus { border-color: var(--truss-green); outline: 1px solid var(--truss-green); }
  #attach { width: 100%; color: var(--vscode-descriptionForeground); }
  #send { min-width: 62px; }
  #agentControls { gap: 9px; padding: 8px 12px 11px; border-top: 1px solid var(--truss-border); background: var(--vscode-sideBar-background); }
  .segmented { border-color: var(--vscode-panel-border); background: var(--truss-surface); }
  .segmented button { color: var(--vscode-descriptionForeground); }
  .segmented button.active { color: #06231b; background: var(--truss-green); box-shadow: none; }
  .quick-model { min-width: 0; padding: 0 7px; border: 1px solid var(--vscode-panel-border); border-radius: 5px; background: var(--truss-surface); }
  .quick-model span { color: var(--truss-green); }
  #quickModel { border: 0; background: transparent; }
  #modelStatus { justify-self: end; max-width: 180px; color: var(--vscode-descriptionForeground); font-size: 11px; }
  @media (max-width: 700px) { #settings.open { grid-template-columns: 1fr; } .settings-section { grid-template-columns: repeat(2, minmax(0, 1fr)); } .settings-section.full-width { grid-column: auto; } }
  @media (max-width: 560px) { .brand-row { grid-template-columns: minmax(0, 1fr) auto; } .header-actions { width: auto; } #headerAction { width: clamp(84px, 32vw, 126px); } .settings-intro { display: block; } .settings-intro p { margin-top: 6px; } .settings-section { grid-template-columns: 1fr; } .settings-section-heading { display: block; } .settings-section-heading span { display: block; margin-top: 3px; text-align: left; } #chat { padding: 10px; } #agentControls { gap: 6px; } #modelStatus { justify-self: start; max-width: none; } }
</style></head><body>
<header><div class="brand-row"><div class="brand-lockup"><img class="brand-mark" src="${logoUri}" alt=""><span class="brand">${brand.productName}</span></div><div class="header-actions"><select id="headerAction" aria-label="Truss actions" title="Truss actions"><option value="">Actions</option><option value="new">New conversation</option><option value="settings">Settings</option><option value="help">Help</option><option value="trussGo">Connect Truss Go</option></select></div></div><div id="telemetry"><div class="telemetry-context" title="Estimated from the active conversation. Local model servers do not consistently report prompt-token usage."><span class="telemetry-label">CONTEXT</span><span id="contextValue">0 / 8.2k</span><div class="meter"><span id="contextMeter"></span></div></div><div title="Estimated from streamed response text"><span class="telemetry-label">SPEED </span><span id="rateValue">-- tok/s</span></div></div></header>
<section id="settings">
  <div class="settings-intro"><div><span>CONNECTION</span><strong>Model &amp; agent settings</strong></div><p>Choose the model, permissions, and internet access for this workspace.</p></div>
  <section class="settings-section full-width"><div class="settings-section-heading"><strong>Provider connection</strong><span>Choose a local server or cloud provider.</span></div><label>Detected server<select id="server"><option value="">Custom / manual</option></select></label><label>Provider<select id="provider"><option value="ollama">Ollama</option><option value="openai-compatible">Compatible API</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="openrouter">OpenRouter</option><option value="groq">Groq</option><option value="together">Together AI</option><option value="gemini">Google Gemini</option><option value="xai">xAI</option><option value="mistral">Mistral AI</option><option value="deepseek">DeepSeek</option><option value="perplexity">Perplexity</option><option value="fireworks">Fireworks AI</option><option value="nvidia-nim">NVIDIA NIM</option><option value="xiaomi-mimo">Xiaomi MiMo</option><option value="sakana-fugu">Sakana Fugu</option><option value="ollama-cloud">Ollama Cloud</option></select></label><label class="full-width-label">Endpoint<input id="endpoint" placeholder="http://127.0.0.1:11434"></label></section>
  <section class="settings-section full-width"><div class="settings-section-heading"><strong>Model &amp; account</strong><span>Keys stay only in VS Code Secret Storage.</span></div><label>Model ID<input id="model" list="models" placeholder="Enter a model ID"><datalist id="models"></datalist></label><div class="model-picker"><span>Discovered models</span><button id="modelPickerButton" type="button" aria-haspopup="listbox" aria-expanded="false">Discover models to choose one</button><div id="modelPickerMenu" hidden><input id="modelPickerSearch" type="search" placeholder="Filter discovered models"><div id="modelPickerOptions" role="listbox" aria-label="Discovered models"></div></div></div><label id="contextWindowSetting"><span id="contextWindowLabel">Context window</span><input id="contextWindow" type="number" min="512" max="1000000" step="512" value="8192"></label><label class="cloud-setting" id="providerAccountSetting">Account<select id="providerAccount"></select></label><label class="cloud-setting" id="providerAccountLabelSetting">Account label<input id="providerAccountLabel" placeholder="Personal"></label><label class="cloud-setting full-width-label" id="providerApiKeySetting">API key<input id="providerApiKey" type="password" autocomplete="off" placeholder="Stored only in VS Code Secret Storage"></label><div id="providerStatus" class="cloud-setting provider-status full-width-label" role="status" aria-live="polite"></div></section>
  <section class="settings-section"><div class="settings-section-heading"><strong>Agent behavior</strong><span>Choose how tools and research work.</span></div><label>Tool permissions<select id="permission"><option value="ask">Ask every time</option><option value="auto-read">Auto-allow read-only</option><option value="auto-all">Auto-allow all tools</option></select></label><label>Internet research<select id="internetAccess"><option value="false">Disabled</option><option value="true">Enabled</option></select></label></section>
  <section class="settings-section full-width"><div class="settings-section-heading"><strong>Master prompt</strong><span>Applied safely to every agent run in this workspace.</span></div><label>Enabled<select id="masterPromptEnabled"><option value="false">Disabled</option><option value="true">Enabled</option></select></label><label class="full-width-label">Template<textarea id="masterPromptTemplate" rows="6" spellcheck="false" placeholder="&lt;project&gt;Work in {{agent.mode}} mode on {{workspace.name}}.&lt;/project&gt;"></textarea></label><div class="provider-status full-width-label">XML remains literal. Dynamic values: {{workspace.name}}, {{workspace.root}}, {{repository.branch}}, {{repository.changedFiles}}, {{agent.mode}}, {{session.id}}, {{date.iso}}.</div></section>
  <div class="actions"><button id="refresh" type="button">Discover models</button><button id="saveProviderAccount" class="cloud-setting" type="button">Save key</button><button id="testProviderConnection" class="cloud-setting" type="button">Test connection</button><button id="removeProviderAccount" class="cloud-setting" type="button">Remove key</button><button id="apply" class="primary" type="button">Apply</button></div>
</section>
<main id="workspace"><aside id="history"><div class="history-title">Conversations</div></aside><section id="chat"><div class="empty">Select a local model in Settings, then ask about the workspace. Use Plan for read-only investigation and Agent when you want the agent to change files or run commands.</div></section></main>
<form id="composer"><div id="slashMenu" role="listbox" hidden></div><div id="attachments" hidden></div><input id="attachmentInput" type="file" multiple hidden><button id="attach" type="button" title="Attach images or text files">Attach files</button><div id="composerRow"><textarea id="prompt" placeholder="Ask about this workspace. Type @/ to attach a file; /help for commands." rows="2"></textarea><button id="stop" type="button">Cancel</button><button id="send" class="primary" type="submit">Send</button></div></form>
  <section id="agentControls" aria-label="Agent controls"><div class="segmented" aria-label="Agent mode"><button data-mode="chat">Chat</button><button data-mode="plan">Plan</button><button data-mode="edit">Agent</button></div><label class="quick-model"><span>MODEL</span><select id="quickModel" title="Switch local model"><option value="">Choose model</option></select></label><span id="modelStatus">Choose a local model</span></section>
<script nonce="${nonce}">
  const vscode = acquireVsCodeApi(); const savedState = vscode.getState(); const state = savedState && typeof savedState === 'object' && Array.isArray(savedState.conversations) ? savedState : { conversations: [], activeId: undefined }; state.conversations = state.conversations.filter((item) => item && typeof item === 'object' && typeof item.id === 'string').map((item) => ({ ...item, title: typeof item.title === 'string' ? item.title : 'Conversation', messages: Array.isArray(item.messages) ? item.messages.filter((message) => message && (message.role === 'user' || message.role === 'assistant') && typeof message.content === 'string') : [], updatedAt: typeof item.updatedAt === 'string' ? item.updatedAt : new Date().toISOString() })); if (!state.conversations.some((item) => item.id === state.activeId)) state.activeId = state.conversations[0]?.id; vscode.setState(state); const history = document.getElementById('history'); const chat = document.getElementById('chat'); const settings = document.getElementById('settings'); const status = document.getElementById('modelStatus'); let persistTimer; const activePlans = new Map(); const streamingConversationIds = new Set(); const activeTools = new Map(); const pendingApprovals = new Map();
  const server = document.getElementById('server'); const provider = document.getElementById('provider'); const endpoint = document.getElementById('endpoint'); const model = document.getElementById('model'); const modelOptions = document.getElementById('models'); const modelPickerButton = document.getElementById('modelPickerButton'); const modelPickerMenu = document.getElementById('modelPickerMenu'); const modelPickerSearch = document.getElementById('modelPickerSearch'); const modelPickerOptions = document.getElementById('modelPickerOptions'); const quickModel = document.getElementById('quickModel'); const permission = document.getElementById('permission'); const internetAccess = document.getElementById('internetAccess'); const masterPromptEnabled = document.getElementById('masterPromptEnabled'); const masterPromptTemplate = document.getElementById('masterPromptTemplate'); const contextWindow = document.getElementById('contextWindow'); const contextValue = document.getElementById('contextValue'); const contextMeter = document.getElementById('contextMeter'); const rateValue = document.getElementById('rateValue'); const prompt = document.getElementById('prompt'); const slashMenu = document.getElementById('slashMenu'); const attachmentInput = document.getElementById('attachmentInput'); const attachmentView = document.getElementById('attachments'); let configuration; let streamStartedAt = 0; let generatedTokens = 0; let workspaceFiles = []; let slashResults = []; let slashIndex = 0; let pendingAttachments = [];
  const providerAccount = document.getElementById('providerAccount'); const providerAccountLabel = document.getElementById('providerAccountLabel'); const providerApiKey = document.getElementById('providerApiKey'); const providerStatus = document.getElementById('providerStatus'); const contextWindowLabel = document.getElementById('contextWindowLabel'); let cloudProviders = []; let providerAccounts = []; let discoveredModels = [];
  const persist = () => { vscode.setState(state); clearTimeout(persistTimer); persistTimer = setTimeout(() => vscode.postMessage({ type: 'saveConversations', state: { conversations: state.conversations, activeId: state.activeId } }), 250); }; const active = () => state.conversations.find((item) => item.id === state.activeId); const byId = (conversationId) => state.conversations.find((item) => item.id === conversationId); const isStreaming = (conversationId) => Boolean(conversationId && streamingConversationIds.has(conversationId)); const renderComposer = () => document.body.classList.toggle('streaming', isStreaming(active()?.id)); const id = () => Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
  const addConversation = () => { const conversation = { id: id(), title: 'New conversation', messages: [], updatedAt: new Date().toISOString() }; state.conversations.unshift(conversation); state.activeId = conversation.id; persist(); return conversation; };
  const current = () => active() || addConversation();
  const estimateTokens = (value) => value.trim() ? Math.ceil(value.trim().length / 4) : 0;
  const formatTokens = (value) => value >= 1000 ? (value / 1000).toFixed(value >= 10000 ? 0 : 1).replace(/\.0$/, '') + 'k' : String(Math.round(value));
  const compareModelIds = (left, right) => left.localeCompare(right, undefined, { numeric: true, sensitivity: 'base' });
  const sortedModelIds = (values) => [...new Set(values.map((value) => value.trim()).filter(Boolean))].sort(compareModelIds);
  const sortedModelEntries = (values) => [...values].sort((left, right) => compareModelIds(left.id, right.id));
  const configuredContextWindow = () => Math.max(512, Math.min(1000000, Number.parseInt(contextWindow.value, 10) || 8192));
  const selectedCloudProvider = () => cloudProviders.find((candidate) => candidate.id === provider.value);
  const selectedProviderAccount = () => providerAccounts.find((candidate) => candidate.id === providerAccount.value && candidate.providerId === provider.value);
  const selectedModelMetadata = () => discoveredModels.find((candidate) => candidate.id === model.value.trim());
  const formatUsd = (amount) => amount < .01 ? '$' + amount.toFixed(4) : '$' + amount.toFixed(amount < 1 ? 3 : 2);
  const modelPickerMetadata = (entry) => { const values = []; if (entry.contextWindow) values.push(formatTokens(entry.contextWindow) + ' ctx'); if (entry.inputCostPerMillion !== undefined && entry.outputCostPerMillion !== undefined) values.push(formatUsd(entry.inputCostPerMillion) + ' in / ' + formatUsd(entry.outputCostPerMillion) + ' out'); return values.join(' · '); };
  const renderModelPicker = () => { const query = modelPickerSearch.value.trim().toLowerCase(); const matches = sortedModelEntries(discoveredModels).filter((entry) => entry.id.toLowerCase().includes(query)).slice(0, 250); const selected = selectedModelMetadata(); modelPickerButton.textContent = selected ? selected.id : discoveredModels.length ? 'Choose a discovered model' : 'Discover models to choose one'; modelPickerButton.title = selected ? modelPickerMetadata(selected) || selected.id : ''; modelPickerOptions.replaceChildren(); if (!matches.length) { const empty = document.createElement('div'); empty.className = 'model-picker-empty'; empty.textContent = discoveredModels.length ? 'No discovered models match that filter.' : 'Use Discover models after selecting a provider.'; modelPickerOptions.append(empty); return; } matches.forEach((entry) => { const option = document.createElement('button'); option.type = 'button'; option.className = 'model-picker-option'; option.setAttribute('role', 'option'); option.setAttribute('aria-selected', String(entry.id === model.value.trim())); const name = document.createElement('span'); name.className = 'model-picker-name'; name.textContent = entry.id; const meta = document.createElement('span'); meta.className = 'model-picker-meta'; meta.textContent = modelPickerMetadata(entry) || 'Metadata unavailable'; option.append(name, meta); option.title = entry.id + (meta.textContent ? ' · ' + meta.textContent : ''); option.onclick = () => { model.value = entry.id; modelPickerSearch.value = ''; modelPickerMenu.hidden = true; modelPickerButton.setAttribute('aria-expanded', 'false'); syncProviderPresentation(providerAccount.value); renderModelPicker(); }; modelPickerOptions.append(option); }); };
  const setModelPickerOpen = (open) => { modelPickerMenu.hidden = !open; modelPickerButton.setAttribute('aria-expanded', String(open)); if (open) { renderModelPicker(); modelPickerSearch.focus(); } };
  const setProviderStatus = (message, kind = '') => { providerStatus.textContent = message || ''; providerStatus.className = 'cloud-setting provider-status ' + kind; };
  const renderProviderAccounts = (preferredId) => {
    const cloud = selectedCloudProvider();
    if (!cloud) { providerAccount.replaceChildren(); return; }
    const accounts = providerAccounts.filter((candidate) => candidate.providerId === cloud.id);
    providerAccount.replaceChildren(...[
      { id: '', label: 'New account' },
      ...accounts.map((account) => ({ id: account.id, label: account.label + (account.hasCredential ? ' · key saved' : ' · key required') })),
    ].map((item) => { const option = document.createElement('option'); option.value = item.id; option.textContent = item.label; return option; }));
    const selected = accounts.find((account) => account.id === preferredId) || accounts.find((account) => account.id === configuration?.credentialAccountId) || accounts[0];
    providerAccount.value = selected?.id || '';
    providerAccountLabel.value = selected?.label || cloud.label + ' account';
    setProviderStatus(selected ? (selected.hasCredential ? 'API key stored securely in VS Code Secret Storage.' : 'This account needs an API key.') : 'Create a named account, then save its API key only in VS Code Secret Storage.', selected?.hasCredential ? 'connected' : '');
  };
  const syncProviderPresentation = (preferredAccountId) => {
    const cloud = selectedCloudProvider();
    document.querySelectorAll('.cloud-setting').forEach((element) => { element.hidden = !cloud; });
    endpoint.readOnly = Boolean(cloud);
    if (cloud) {
      endpoint.value = cloud.baseUrl;
      contextWindow.disabled = true;
      contextWindowLabel.textContent = 'Cloud model context';
      contextWindow.title = 'Cloud models use provider metadata when advertised; otherwise Truss uses a conservative 8k context fallback.';
      const metadata = selectedModelMetadata();
      contextWindow.value = metadata?.contextWindow || (configuration?.provider === cloud.id ? configuration.contextWindow : 8192) || 8192;
      renderProviderAccounts(preferredAccountId);
    } else {
      contextWindow.disabled = false;
      contextWindowLabel.textContent = 'Context window';
      contextWindow.title = 'Truss detects the active local model context when the endpoint provides it.';
      providerApiKey.value = '';
      providerAccount.replaceChildren();
    }
    renderTelemetry();
  };
  const renderTelemetry = () => { const conversation = active(); const used = (conversation ? conversation.messages.reduce((total, item) => total + estimateTokens(item.content), 0) : 0) + 400; const limit = configuredContextWindow(); const ratio = Math.min(1, used / limit); contextValue.textContent = formatTokens(used) + ' / ' + formatTokens(limit); contextMeter.style.width = (ratio * 100).toFixed(1) + '%'; contextMeter.className = ratio >= .9 ? 'critical' : ratio >= .7 ? 'warning' : ratio > 0 ? 'active' : ''; const elapsed = streamStartedAt ? (performance.now() - streamStartedAt) / 1000 : 0; rateValue.textContent = generatedTokens && elapsed > 0 ? (generatedTokens / elapsed).toFixed(1) + ' tok/s' : '-- tok/s'; };
  const deleteConversation = (conversationId) => { const conversation = byId(conversationId); if (!conversation) return; const wasActive = state.activeId === conversationId; streamingConversationIds.delete(conversationId); activeTools.delete(conversationId); pendingApprovals.delete(conversationId); activePlans.delete(conversationId); state.conversations = state.conversations.filter((item) => item.id !== conversationId); if (wasActive) state.activeId = state.conversations[0]?.id; vscode.postMessage({ type: 'deleteConversation', conversationId }); persist(); renderHistory(); renderChat(); };
  const renderHistory = () => { history.replaceChildren(); const label = document.createElement('div'); label.className = 'history-title'; label.textContent = 'Conversations'; history.append(label); state.conversations.forEach((conversation) => { const row = document.createElement('div'); row.className = 'conversation-row'; const button = document.createElement('button'); button.className = 'conversation' + (conversation.id === state.activeId ? ' active' : ''); button.textContent = conversation.title + (isStreaming(conversation.id) ? ' · Working' : ''); button.onclick = () => { state.activeId = conversation.id; persist(); renderHistory(); renderChat(); vscode.postMessage({ type: 'selectConversation', conversationId: conversation.id }); }; const remove = document.createElement('button'); remove.className = 'delete-conversation'; remove.type = 'button'; remove.textContent = 'x'; remove.title = 'Delete conversation'; remove.setAttribute('aria-label', 'Delete ' + conversation.title); remove.onclick = () => deleteConversation(conversation.id); row.append(button, remove); history.append(row); }); renderComposer(); };
  const appendInlineMarkdown = (parent, text) => { const token = /(\`[^\`]*\`)|(\[([^\]]+)\]\(([^\s)]+)\))|(\*\*([^*]+)\*\*)|(\*([^*]+)\*)/g; let cursor = 0; for (const match of text.matchAll(token)) { const index = match.index || 0; if (index > cursor) parent.append(document.createTextNode(text.slice(cursor, index))); if (match[1]) { const code = document.createElement('code'); code.textContent = match[1].slice(1, -1); parent.append(code); } else if (match[2]) { const link = document.createElement('a'); const href = match[4] || ''; link.textContent = match[3] || href; if (/^(https?:|mailto:)/i.test(href)) { link.href = href; link.target = '_blank'; link.rel = 'noreferrer'; } parent.append(link); } else if (match[5]) { const strong = document.createElement('strong'); strong.textContent = match[6] || ''; parent.append(strong); } else if (match[7]) { const emphasis = document.createElement('em'); emphasis.textContent = match[8] || ''; parent.append(emphasis); } cursor = index + match[0].length; } if (cursor < text.length) parent.append(document.createTextNode(text.slice(cursor))); };
  const appendHighlightedCode = (parent, code) => { const token = /(\/\/[^\n]*|#[^\n]*)|("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')|(\b(?:const|let|var|function|return|if|else|for|while|class|interface|type|import|export|from|async|await|new|public|private|static|def|fn|match|use|package)\b)|(\b\d+(?:\.\d+)?\b)/g; let cursor = 0; for (const match of code.matchAll(token)) { const index = match.index || 0; if (index > cursor) parent.append(document.createTextNode(code.slice(cursor, index))); const span = document.createElement('span'); span.className = match[1] ? 'token-comment' : match[2] ? 'token-string' : match[3] ? 'token-keyword' : 'token-number'; span.textContent = match[0]; parent.append(span); cursor = index + match[0].length; } if (cursor < code.length) parent.append(document.createTextNode(code.slice(cursor))); };
  const renderMarkdown = (container, content) => { const lines = content.replace(/\r\n/g, '\n').split('\n'); for (let index = 0; index < lines.length;) { const line = lines[index]; const fence = line.match(/^\`\`\`([^\s]*)\s*$/); if (fence) { const language = fence[1] || 'text'; const code = []; index += 1; while (index < lines.length && !/^\`\`\`\s*$/.test(lines[index])) code.push(lines[index++]); if (index < lines.length) index += 1; const block = document.createElement('div'); block.className = 'code-block'; const label = document.createElement('div'); label.className = 'code-language'; label.textContent = language; const pre = document.createElement('pre'); const codeElement = document.createElement('code'); appendHighlightedCode(codeElement, code.join('\n')); pre.append(codeElement); block.append(label, pre); container.append(block); continue; } const heading = line.match(/^(#{1,4})\s+(.+)$/); if (heading) { const element = document.createElement('h' + heading[1].length); appendInlineMarkdown(element, heading[2]); container.append(element); index += 1; continue; } const list = line.match(/^[-*+]\s+(.+)$/); if (list) { const listElement = document.createElement('ul'); do { const item = document.createElement('li'); appendInlineMarkdown(item, lines[index].replace(/^[-*+]\s+/, '')); listElement.append(item); index += 1; } while (index < lines.length && /^[-*+]\s+/.test(lines[index])); container.append(listElement); continue; } const quote = line.match(/^>\s?(.*)$/); if (quote) { const blockquote = document.createElement('blockquote'); appendInlineMarkdown(blockquote, quote[1]); container.append(blockquote); index += 1; continue; } if (!line.trim()) { index += 1; continue; } const paragraph = document.createElement('p'); const paragraphLines = [line]; index += 1; while (index < lines.length && lines[index].trim() && !/^(#{1,4}\s|\`\`\`|[-*+]\s+|>\s?)/.test(lines[index])) paragraphLines.push(lines[index++]); appendInlineMarkdown(paragraph, paragraphLines.join('\n')); container.append(paragraph); } };
  const message = (role, content, attachments = [], streaming = false) => { const element = document.createElement('div'); element.className = 'message ' + role; const label = document.createElement('div'); label.className = 'message-header'; label.textContent = role === 'user' ? 'YOU' : 'AGENT'; const body = document.createElement('div'); if (role === 'assistant' && !content && streaming) { body.className = 'thinking'; body.textContent = 'Thinking...'; } else { body.className = 'markdown'; renderMarkdown(body, content); } element.append(label, body); if (attachments.length) { const list = document.createElement('div'); list.className = 'message-attachments'; attachments.forEach((attachment) => { const item = document.createElement('div'); item.className = 'attachment'; if (attachment.kind === 'image' && attachment.data) { const image = document.createElement('img'); image.src = attachment.data; image.alt = attachment.name; item.append(image); } const name = document.createElement('span'); name.textContent = attachment.name; item.append(name); list.append(item); }); element.append(list); } return { element, body }; };
  const planView = (plan) => { if (!plan) return undefined; const view = document.createElement('section'); view.className = 'plan'; const title = document.createElement('strong'); title.textContent = plan.title; view.append(title); plan.steps.forEach((step) => { const row = document.createElement('div'); row.className = 'plan-step ' + step.status; row.textContent = (step.status === 'completed' ? '[x] ' : step.status === 'in_progress' ? '[..] ' : '[ ] ') + step.content; view.append(row); }); return view; };
  const pendingApprovalView = (conversationId, approval) => { const item = document.createElement('div'); item.className = 'tool'; item.textContent = 'Allow ' + approval.tool + ' ' + JSON.stringify(approval.input) + '? '; const allow = document.createElement('button'); allow.textContent = 'Allow'; const deny = document.createElement('button'); deny.textContent = 'Deny'; const resolve = (approved) => { pendingApprovals.delete(conversationId); vscode.postMessage({ type: 'toolApproval', conversationId, requestId: approval.requestId, callId: approval.callId, approved }); renderChat(); }; allow.onclick = () => resolve(true); deny.onclick = () => resolve(false); item.append(allow, deny); return item; };
  const renderChat = () => { chat.replaceChildren(); const conversation = active(); renderComposer(); const plan = planView(conversation && activePlans.get(conversation.id)); if (plan) chat.append(plan); if (!conversation || !conversation.messages.length) { const empty = document.createElement('div'); empty.className = 'empty'; empty.textContent = 'Select a local model in Settings, then ask about the workspace. Use Plan for read-only investigation and Agent when you want the agent to change files or run commands.'; chat.append(empty); renderTelemetry(); return; } conversation.messages.forEach((item) => { const view = message(item.role, item.content, item.attachments || [], isStreaming(conversation.id)); chat.append(view.element); }); const activeTool = activeTools.get(conversation.id); if (activeTool) { const item = document.createElement('div'); item.className = 'tool'; item.textContent = 'Running tool: ' + activeTool; chat.append(item); } const approval = pendingApprovals.get(conversation.id); if (approval) chat.append(pendingApprovalView(conversation.id, approval)); chat.scrollTop = chat.scrollHeight; renderTelemetry(); };
  const addMessage = (role, content, attachments) => { const conversation = current(); conversation.messages.push({ role, content, ...(attachments && attachments.length ? { attachments } : {}) }); conversation.updatedAt = new Date().toISOString(); if (role === 'user' && conversation.title === 'New conversation') conversation.title = content.replace(/\s+/g, ' ').slice(0, 32) || conversation.title; persist(); renderHistory(); renderChat(); return conversation.messages.length - 1; };
  const configurationValue = () => { const cloud = selectedCloudProvider(); const metadata = selectedModelMetadata(); return { provider: provider.value, baseUrl: cloud ? cloud.baseUrl : endpoint.value.trim(), model: model.value.trim(), ...(cloud && providerAccount.value ? { credentialAccountId: providerAccount.value } : {}), mode: configuration ? configuration.mode : 'chat', permission: permission.value, contextWindow: cloud ? (metadata?.contextWindow || 8192) : configuredContextWindow(), internetAccess: internetAccess.value === 'true', masterPrompt: { enabled: masterPromptEnabled.value === 'true', template: masterPromptTemplate.value }, mcpServers: configuration?.mcpServers || {} }; };
  const postConfigure = () => vscode.postMessage({ type: 'configure', configuration: configurationValue() });
  const beginStream = () => { streamStartedAt = performance.now(); generatedTokens = 0; renderTelemetry(); };
  const slashQuery = () => { const beforeCursor = prompt.value.slice(0, prompt.selectionStart || prompt.value.length); const match = beforeCursor.match(/(?:^|\s)@\/([^\s]*)$/); return match ? { start: beforeCursor.length - match[1].length - 2, query: match[1] } : undefined; };
  const fuzzyScore = (path, query) => { const target = path.toLowerCase(); const needle = query.toLowerCase(); let position = 0; let score = 0; for (const character of needle) { const next = target.indexOf(character, position); if (next === -1) return undefined; score += next - position; position = next + 1; } return score + (target.includes(needle) ? -30 : 0) + path.length / 1000; };
  const insertSlashFile = (path) => { const query = slashQuery(); if (!query) return; const cursor = prompt.selectionStart || prompt.value.length; prompt.value = prompt.value.slice(0, query.start) + '@/' + path + ' ' + prompt.value.slice(cursor); const nextCursor = query.start + path.length + 3; prompt.setSelectionRange(nextCursor, nextCursor); slashMenu.hidden = true; prompt.focus(); };
  const renderSlashMenu = () => { const query = slashQuery(); if (!query) { slashMenu.hidden = true; slashResults = []; return; } slashResults = workspaceFiles.map((path) => ({ path, score: fuzzyScore(path, query.query) })).filter((item) => item.score !== undefined).sort((left, right) => left.score - right.score || left.path.localeCompare(right.path)).slice(0, 8).map((item) => item.path); if (!slashResults.length) { slashMenu.hidden = true; return; } slashIndex = Math.min(slashIndex, slashResults.length - 1); slashMenu.replaceChildren(...slashResults.map((path, index) => { const option = document.createElement('button'); option.type = 'button'; option.className = 'slash-option' + (index === slashIndex ? ' active' : ''); option.setAttribute('role', 'option'); option.setAttribute('aria-selected', String(index === slashIndex)); option.textContent = path; option.onmousedown = (event) => { event.preventDefault(); insertSlashFile(path); }; return option; })); slashMenu.hidden = false; };
  const attachedPaths = (text) => [...new Set([...text.matchAll(/(?:^|\s)@\/([^\s]+)/g)].map((match) => match[1].replaceAll('\\', '/')).filter((path) => workspaceFiles.includes(path)))];
  const renderAttachments = () => { attachmentView.hidden = !pendingAttachments.length; attachmentView.replaceChildren(...pendingAttachments.map((attachment) => { const item = document.createElement('div'); item.className = 'attachment'; if (attachment.kind === 'image' && attachment.data) { const image = document.createElement('img'); image.src = attachment.data; image.alt = ''; item.append(image); } const name = document.createElement('span'); name.textContent = attachment.name; const remove = document.createElement('button'); remove.type = 'button'; remove.textContent = 'x'; remove.title = 'Remove ' + attachment.name; remove.onclick = () => { pendingAttachments = pendingAttachments.filter((candidate) => candidate.id !== attachment.id); renderAttachments(); }; item.append(name, remove); return item; })); };
  const toAttachment = async (file) => { if (!file.name) throw new Error('The selected file has no name.'); if (file.size > 4 * 1024 * 1024) throw new Error(file.name + ' exceeds the 4 MB attachment limit.'); if (file.type.startsWith('image/')) { if (!['image/png', 'image/jpeg', 'image/webp', 'image/gif'].includes(file.type)) throw new Error(file.name + ' uses an unsupported image type.'); const data = await new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => typeof reader.result === 'string' ? resolve(reader.result) : reject(new Error('Unable to read ' + file.name)); reader.onerror = () => reject(new Error('Unable to read ' + file.name)); reader.readAsDataURL(file); }); return { id: 'attachment-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 8), kind: 'image', name: file.name, mediaType: file.type, data, size: file.size }; } if (!(file.type.startsWith('text/') || /\.(md|mdx|txt|json|jsonc|ya?ml|toml|ini|cfg|conf|csv|ts|tsx|js|jsx|mjs|cjs|css|html?|xml|svg|py|go|rs|java|php|rb|sh|sql)$/i.test(file.name))) throw new Error(file.name + ' is not a supported text file.'); const text = await file.text(); if (text.includes('\u0000')) throw new Error(file.name + ' appears to be binary.'); return { id: 'attachment-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 8), kind: 'file', name: file.name, mediaType: file.type || 'text/plain', text: text.slice(0, 120000), size: file.size }; };
  const addFiles = async (files) => { const selected = [...files]; if (!selected.length) return; if (pendingAttachments.length + selected.length > 5) { status.textContent = 'Attach up to five files.'; return; } if (pendingAttachments.reduce((total, item) => total + item.size, 0) + selected.reduce((total, item) => total + item.size, 0) > 12 * 1024 * 1024) { status.textContent = 'Attachments exceed the 12 MB total limit.'; return; } try { pendingAttachments = [...pendingAttachments, ...await Promise.all(selected.map(toAttachment))]; renderAttachments(); } catch (error) { status.textContent = error && error.message ? error.message : String(error); } };
  const sendChat = (text) => { const conversation = current(); if (isStreaming(conversation.id)) return; const history = conversation.messages.map((message) => ({ role: message.role, content: message.content, ...(message.attachments ? { attachments: message.attachments } : {}) })); const attachments = pendingAttachments; streamingConversationIds.add(conversation.id); addMessage('user', text, attachments); addMessage('assistant', ''); prompt.value = ''; attachmentInput.value = ''; pendingAttachments = []; renderAttachments(); slashMenu.hidden = true; beginStream(); vscode.postMessage({ type: 'send', prompt: text, conversationId: conversation.id, history, attachments, attachedPaths: attachedPaths(text) }); };
  const headerAction = document.getElementById('headerAction'); const settingsAction = headerAction.querySelector('option[value="settings"]'); const setSettingsOpen = (open) => { settings.classList.toggle('open', open); settingsAction.textContent = open ? 'Hide settings' : 'Settings'; }; headerAction.onchange = () => { const action = headerAction.value; headerAction.value = ''; if (action === 'new') { addConversation(); renderHistory(); renderChat(); vscode.postMessage({ type: 'newConversation' }); } if (action === 'settings') setSettingsOpen(!settings.classList.contains('open')); if (action === 'help') sendChat('/help'); if (action === 'trussGo') vscode.postMessage({ type: 'connectTrussGo' }); };
  document.getElementById('refresh').onclick = () => { try { if (selectedCloudProvider()) setProviderStatus(providerApiKey.value.trim() ? 'Discovering models from the provider…' : 'Checking the saved provider key…'); vscode.postMessage({ type: 'discover', configuration: configurationValue(), ...(providerApiKey.value.trim() ? { apiKey: providerApiKey.value } : {}) }); } catch (error) { status.textContent = error.message || String(error); } }; document.getElementById('apply').onclick = () => { try { postConfigure(); } catch (error) { status.textContent = error.message || String(error); } };
  document.getElementById('saveProviderAccount').onclick = () => { try { const cloud = selectedCloudProvider(); if (!cloud) return; const next = configurationValue(); if (!next.model) return setProviderStatus('Enter a model ID before saving this account.', 'failed'); if (!providerApiKey.value.trim()) return setProviderStatus('Enter an API key before saving this account.', 'failed'); vscode.postMessage({ type: 'saveProviderAccount', provider: cloud.id, accountId: providerAccount.value || undefined, accountLabel: providerAccountLabel.value.trim(), apiKey: providerApiKey.value, configuration: next }); } catch (error) { setProviderStatus(error.message || String(error), 'failed'); } };
  document.getElementById('testProviderConnection').onclick = () => { try { const cloud = selectedCloudProvider(); if (cloud) setProviderStatus('Testing provider connection…'); vscode.postMessage({ type: 'testProviderConnection', configuration: configurationValue(), ...(providerApiKey.value.trim() ? { apiKey: providerApiKey.value } : {}) }); } catch (error) { setProviderStatus(error.message || String(error), 'failed'); } };
  document.getElementById('removeProviderAccount').onclick = () => { if (!providerAccount.value) return setProviderStatus('Choose a saved account before removing a key.', 'failed'); vscode.postMessage({ type: 'removeProviderAccount', accountId: providerAccount.value }); };
  contextWindow.oninput = renderTelemetry;
  const setMode = (mode) => { configuration = { ...(configuration || configurationValue()), mode }; document.querySelectorAll('[data-mode]').forEach((button) => button.classList.toggle('active', button.dataset.mode === mode)); postConfigure(); };
  document.querySelectorAll('[data-mode]').forEach((button) => button.onclick = () => setMode(button.dataset.mode));
  quickModel.onchange = () => { const value = quickModel.value.trim(); if (!value || value === model.value) return; model.value = value; configuration = { ...(configuration || configurationValue()), model: value }; postConfigure(); };
  provider.onchange = () => { model.value = ''; modelPickerSearch.value = ''; discoveredModels = []; setModelPickerOpen(false); syncProviderPresentation(); renderModelPicker(); vscode.postMessage({ type: 'discover', configuration: configurationValue(), ...(providerApiKey.value.trim() ? { apiKey: providerApiKey.value } : {}) }); };
  providerAccount.onchange = () => { syncProviderPresentation(providerAccount.value); };
  model.onchange = () => { syncProviderPresentation(providerAccount.value); renderModelPicker(); };
  modelPickerButton.onclick = () => setModelPickerOpen(modelPickerMenu.hidden);
  modelPickerSearch.oninput = renderModelPicker;
  document.addEventListener('pointerdown', (event) => { if (!(event.target instanceof Element) || !event.target.closest('.model-picker')) setModelPickerOpen(false); });
  server.onchange = () => { if (!server.value) return; const selected = JSON.parse(server.value); provider.value = selected.kind; endpoint.value = selected.baseUrl; syncProviderPresentation(); vscode.postMessage({ type: 'discover', configuration: configurationValue(), ...(providerApiKey.value.trim() ? { apiKey: providerApiKey.value } : {}) }); };
  document.getElementById('attach').onclick = () => attachmentInput.click(); attachmentInput.onchange = () => addFiles(attachmentInput.files || []); document.getElementById('composer').ondragover = (event) => event.preventDefault(); document.getElementById('composer').ondrop = (event) => { event.preventDefault(); addFiles(event.dataTransfer.files || []); };
  prompt.oninput = () => { slashIndex = 0; renderSlashMenu(); };
  prompt.onkeydown = (event) => { if (event.ctrlKey && event.key === 'Enter') { event.preventDefault(); if (isStreaming(active()?.id)) return; const text = prompt.value.trim() || (pendingAttachments.length ? 'Review the attached files.' : ''); if (text) sendChat(text); return; } if (slashMenu.hidden || !slashResults.length) return; if (event.key === 'ArrowDown') { event.preventDefault(); slashIndex = (slashIndex + 1) % slashResults.length; renderSlashMenu(); } if (event.key === 'ArrowUp') { event.preventDefault(); slashIndex = (slashIndex - 1 + slashResults.length) % slashResults.length; renderSlashMenu(); } if ((event.key === 'Enter' || event.key === 'Tab') && slashResults[slashIndex]) { event.preventDefault(); insertSlashFile(slashResults[slashIndex]); } if (event.key === 'Escape') slashMenu.hidden = true; };
  document.getElementById('composer').onsubmit = (event) => { event.preventDefault(); const text = prompt.value.trim() || (pendingAttachments.length ? 'Review the attached files.' : ''); if (!text) return; sendChat(text); };
  document.getElementById('stop').onclick = () => { const conversation = active(); if (conversation) vscode.postMessage({ type: 'stop', conversationId: conversation.id }); };
  window.addEventListener('message', ({ data: message }) => {
    if (message.type === 'state') {
      const next = message.state;
      configuration = next.configuration;
      cloudProviders = Array.isArray(next.cloudProviders) ? next.cloudProviders : [];
      providerAccounts = Array.isArray(next.providerAccounts) ? next.providerAccounts : [];
      discoveredModels = Array.isArray(next.models) ? sortedModelEntries(next.models) : [];
      provider.value = configuration.provider;
      endpoint.value = configuration.baseUrl;
      model.value = configuration.model;
      permission.value = configuration.permission;
      internetAccess.value = configuration.internetAccess ? 'true' : 'false';
      masterPromptEnabled.value = configuration.masterPrompt?.enabled ? 'true' : 'false';
      masterPromptTemplate.value = configuration.masterPrompt?.template || '';
      contextWindow.value = configuration.contextWindow || 8192;
      modelOptions.replaceChildren(...discoveredModels.map((entry) => { const option = document.createElement('option'); option.value = entry.id; option.label = entry.contextWindow ? entry.id + ' · ' + formatTokens(entry.contextWindow) + ' context' : entry.id; return option; }));
      renderModelPicker();
      const quickModels = sortedModelIds([configuration.model, ...discoveredModels.map((entry) => entry.id)]);
      quickModel.replaceChildren(...(quickModels.length ? quickModels : ['']).map((name) => { const option = document.createElement('option'); option.value = name; option.textContent = name || 'Choose model'; return option; }));
      quickModel.value = configuration.model;
      server.replaceChildren(...[{ label: 'Custom / manual', kind: '', baseUrl: '' }, ...(next.endpoints || [])].map((item) => { const option = document.createElement('option'); option.value = item.kind ? JSON.stringify(item) : ''; option.textContent = item.label + (item.baseUrl ? ' (' + item.baseUrl + ')' : ''); return option; }));
      document.querySelectorAll('[data-mode]').forEach((button) => button.classList.toggle('active', button.dataset.mode === configuration.mode));
      syncProviderPresentation(configuration.credentialAccountId);
      const providerLabel = selectedCloudProvider()?.label || configuration.provider;
      status.textContent = configuration.model ? providerLabel + ' / ' + configuration.model : 'Choose a model in Settings';
      renderTelemetry();
    }
    if (message.type === 'conversations') { state.conversations = message.state.conversations || []; state.activeId = message.state.activeId; vscode.setState(state); renderHistory(); renderChat(); }
    if (message.type === 'workspaceFiles') { workspaceFiles = Array.isArray(message.files) ? message.files : []; }
    if (message.type === 'plan') { const conversation = message.conversationId ? byId(message.conversationId) : active(); if (conversation) { activePlans.set(conversation.id, message.plan); if (conversation.id === state.activeId) renderChat(); } }
    if (message.type === 'assistantStart') { const conversation = byId(message.conversationId); if (conversation) { streamingConversationIds.add(conversation.id); renderHistory(); if (conversation.id === state.activeId) renderChat(); } }
    if (message.type === 'delta') { const conversation = byId(message.conversationId); const last = conversation && conversation.messages.at(-1); if (last && last.role === 'assistant') { last.content += message.text; if (conversation.id === state.activeId) generatedTokens += estimateTokens(message.text); conversation.updatedAt = new Date().toISOString(); persist(); if (conversation.id === state.activeId) renderChat(); else renderHistory(); } }
    if (message.type === 'tool') { const conversation = byId(message.conversationId); if (conversation) { activeTools.set(conversation.id, message.tool); if (conversation.id === state.activeId) renderChat(); } }
    if (message.type === 'approval') { const conversation = byId(message.conversationId); if (conversation) { pendingApprovals.set(conversation.id, message); if (conversation.id === state.activeId) renderChat(); else renderHistory(); } }
    if (message.type === 'session') { persist(); }
    if (message.type === 'runtimeReset') { persist(); }
    if (message.type === 'workspaceCommand') { current(); addMessage('user', message.command); addMessage('assistant', message.message); }
    if (message.type === 'assistantEnd') { const conversation = byId(message.conversationId); if (conversation) { const last = conversation.messages.at(-1); if (message.aborted && last?.role === 'assistant' && !last.content) last.content = 'Cancelled.'; streamingConversationIds.delete(conversation.id); activeTools.delete(conversation.id); pendingApprovals.delete(conversation.id); persist(); renderHistory(); if (conversation.id === state.activeId) renderChat(); else renderTelemetry(); } }
    if (message.type === 'conversationReset') { renderHistory(); renderChat(); }
    if (message.type === 'error') { const conversation = message.conversationId ? byId(message.conversationId) : undefined; if (!conversation) { status.textContent = message.message || 'Truss error'; return; } const last = conversation.messages.at(-1); if (last?.role === 'assistant' && !last.content) last.content = 'Error: ' + message.message; else conversation.messages.push({ role: 'assistant', content: 'Error: ' + message.message }); conversation.updatedAt = new Date().toISOString(); streamingConversationIds.delete(conversation.id); activeTools.delete(conversation.id); pendingApprovals.delete(conversation.id); persist(); renderHistory(); if (conversation.id === state.activeId) renderChat(); }
    if (message.type === 'providerAccountSaved') { providerApiKey.value = ''; setProviderStatus(message.message, 'connected'); }
    if (message.type === 'providerAccountRemoved') { providerApiKey.value = ''; setProviderStatus(message.message); }
    if (message.type === 'providerAccountError') setProviderStatus(message.message, 'failed');
    if (message.type === 'connectionResult') setProviderStatus(message.message, message.status === 'connected' ? 'connected' : 'failed');
  });
  renderHistory(); renderChat(); vscode.postMessage({ type: 'ready' });
</script></body></html>`;
}
