import {
  AgentCoordinator,
  AgentRuntime,
  ApiKeyCredential,
  CompositeContextManager,
  EventBus,
  FileWorkspaceMemoryStore,
  FileWorkspacePlanStore,
  InMemoryAgentProfileStore,
  InMemorySessionStore,
  ModelRequestError,
  ToolRegistry,
  createUpdatePlanTool,
  defaultProviderAccountId,
  executeWorkspaceCommand,
  grepTool,
  isProviderAccount,
  listDirectoryTool,
  readFileTool,
  registerCoreTools,
  registerWebTools,
  searchFilesTool,
  toRemoteSessionEvent,
  workspaceCommandHelp,
  type AgentApprovalController,
  type AgentCoordinatorEvent,
  type AgentProfile,
  type AgentProfileStore,
  type AgentProviderBinding,
  type AgentRunHistoryStore,
  type AgentRunSummary,
  type AgentRuntimeFactory,
  type ChatAttachment,
  type ChatMessage,
  type ContextBlock,
  type CreatedManagedAgentRuntime,
  type CredentialProvider,
  type JsonObject,
  type ManagedAgentMode,
  type ModelProvider,
  type ModelRequest,
  type ModelStreamEvent,
  type ProviderAccount,
  type RemoteAgentEvent,
  type RemoteAgentProfile,
  type RemoteAgentRunSummary,
  type RemoteCommandResult,
  type RemoteHostCapabilities,
  type RemoteMcpServerStatus,
  type RemoteToolApprovalMode,
  type RemoteWorkspace,
  type RuntimeEvent,
  type Session,
  type ToolApproval,
  type ToolCall,
  type WorkspacePlan,
} from "./index.js";
import { describe, expect, it } from "vitest";

type ConsumerContract = readonly [
  AgentApprovalController,
  AgentCoordinatorEvent,
  AgentProfile,
  AgentProfileStore,
  AgentProviderBinding,
  AgentRunHistoryStore,
  AgentRunSummary,
  AgentRuntimeFactory,
  ChatAttachment,
  ChatMessage,
  ContextBlock,
  CreatedManagedAgentRuntime,
  CredentialProvider,
  JsonObject,
  ManagedAgentMode,
  ModelProvider,
  ModelRequest,
  ModelStreamEvent,
  ProviderAccount,
  RemoteAgentEvent,
  RemoteAgentProfile,
  RemoteAgentRunSummary,
  RemoteCommandResult,
  RemoteHostCapabilities,
  RemoteMcpServerStatus,
  RemoteToolApprovalMode,
  RemoteWorkspace,
  RuntimeEvent,
  Session,
  ToolApproval,
  ToolCall,
  WorkspacePlan,
];

const publicValues = [
  AgentCoordinator,
  AgentRuntime,
  ApiKeyCredential,
  CompositeContextManager,
  EventBus,
  FileWorkspaceMemoryStore,
  FileWorkspacePlanStore,
  InMemoryAgentProfileStore,
  InMemorySessionStore,
  ModelRequestError,
  ToolRegistry,
  createUpdatePlanTool,
  defaultProviderAccountId,
  executeWorkspaceCommand,
  grepTool,
  isProviderAccount,
  listDirectoryTool,
  readFileTool,
  registerCoreTools,
  registerWebTools,
  searchFilesTool,
  toRemoteSessionEvent,
  workspaceCommandHelp,
] as const;

describe("runtime public API", () => {
  it("keeps the contracts and values consumed by shared packages available", () => {
    const contract: ConsumerContract | undefined = undefined;
    expect(contract).toBeUndefined();
    expect(publicValues.every((value) => value !== undefined)).toBe(true);
  });
});
